### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [meteonomiqs/gtm-weather#2]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUriComponent should be used on user provided values that are then used as parameters in your url. These methods take in a single text argument and return a URI Encoded string. You should use this method on data.status, data.temperature, data.precipitation, data.windchill and cookiega when generating the url
let url = encodeUri(endpoint)+"?s="+data.status+"&t="+data.temperature+"&p="+data.precipitation+"&w="+data.windchill+"&c="+cookiega;

**Comment by carsten-herbe-wettercom** [comment]
@praveena-pappu thanks for your feedback! We have changed the implementation accordingly? Could you please check and kindly continue with the gallery submission process? Thanks!
